# app.yaml

runtime: python312

# ADICIONE ESTE BLOCO PARA CONFIGURAR O NÍVEL GRATUITO
automatic_scaling:
  min_instances: 0  # Permite que o site "durma" para custo zero quando não há visitas
  max_instances: 1  # Limita a no máximo 1 instância para evitar custos inesperados

entrypoint: gunicorn -b :$PORT agendamento_system.wsgi:application --workers 2

env_variables:
  # ... (suas variáveis de ambiente, como SECRET_KEY, DB_PASSWORD, etc.) ...

handlers:
- url: /static
  static_dir: staticfiles/

- url: /.*
  script: auto