# app.yaml - Ficheiro de configuração para o Google App Engine

# Define a versão do Python que a nuvem deve usar
runtime: python312 

# O entrypoint diz ao Google como iniciar o nosso servidor web.
# Usamos o Gunicorn, um servidor robusto para produção.
# O comando '--workers 2' é uma otimização para lidar com mais de um acesso ao mesmo tempo.
entrypoint: gunicorn -b :$PORT agendamento_system.wsgi:application --workers 2

# env_variables são as nossas "variáveis de ambiente" para a nuvem.
# É aqui que você vai colocar as suas chaves e senhas secretas.
# IMPORTANTE: Substitua os valores 'SUA_...' pelos seus dados reais.
env_variables:
  # --- Chaves de Segurança do Django e SendGrid ---
  SECRET_KEY: 'xfqcidyehecnvpw'
  SENDGRID_API_KEY: ''
  
  # Em produção, o DEBUG deve ser sempre False por segurança.
  DEBUG: 'False'

  # --- Credenciais do Banco de Dados (Cloud SQL) ---
  # O Nome da Conexão da sua instância, que já temos
  CLOUD_SQL_CONNECTION_NAME: 'agendamentos-system:southamerica-east1:bellcilios-db'
  DB_NAME: 'bellcilios_db'
  DB_USER: 'root'
  DB_PASSWORD: 'TDo1/"iMMb?%[2G}UI'

# handlers direcionam o tráfego. Esta seção é para servir os ficheiros estáticos
# (CSS, JavaScript, imagens) de forma eficiente.
handlers:
- url: /static
  static_dir: staticfiles/

- url: /.*
  script: auto

