# Generated by Django 5.2.1 on 2025-06-16 02:41

import agendamentos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Este e-mail já está cadastrado.'}, max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, validators=[agendamentos.models.validate_telefone])),
                ('cpf', models.CharField(error_messages={'unique': 'Este CPF já está cadastrado.'}, help_text='Digite apenas os 11 números do CPF.', max_length=11, unique=True, validators=[agendamentos.models.validate_cpf])),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('duracao', models.IntegerField(help_text='Duração do serviço em minutos')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(error_messages={'unique': 'Este horário já foi agendado.'}, unique=True)),
                ('status', models.CharField(choices=[('Confirmado', 'Confirmado'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado'), ('Realizado', 'Realizado')], default='Confirmado', max_length=20)),
                ('lembrete_enviado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agendamentos.cliente')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='agendamentos.servico')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
    ]
