# Generated by Django 5.2.1 on 2025-06-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_agendamento_data_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='duracao',
        ),
        migrations.AddField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/', verbose_name='Imagem do Serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
