# Generated by Django 5.2.1 on 2025-07-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_cliente_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='duracao',
            field=models.IntegerField(default=60, help_text='Duração do serviço em minutos'),
        ),
    ]
