# Generated by Django 5.2.1 on 2025-09-13 14:42

import agendamentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_servico_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, error_messages={'unique': 'Este CPF já está cadastrado.'}, help_text='Digite apenas os 11 números do CPF.', max_length=11, null=True, unique=True, validators=[agendamentos.models.validate_cpf]),
        ),
    ]
