# Generated by Django 5.2.1 on 2025-09-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_alter_agendamento_status_notificacao_servicoimagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoAluna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluna', models.CharField(max_length=120)),
                ('tecnica', models.CharField(help_text='Ex.: Fio a Fio, Volume Russo…', max_length=120)),
                ('foto', models.ImageField(upload_to='resultados/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Confirmado', 'Confirmado'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado'), ('Realizado', 'Realizado')], default='Confirmado', max_length=20),
        ),
    ]
