# Generated by Django 5.2.1 on 2025-09-18 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_resultadoaluna_alter_agendamento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='provas/')),
                ('legenda', models.CharField(blank=True, max_length=160)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prova social',
                'verbose_name_plural': 'Provas sociais',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.AlterModelOptions(
            name='resultadoaluna',
            options={'ordering': ['ordem', '-criado_em']},
        ),
        migrations.AddField(
            model_name='resultadoaluna',
            name='ordem',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Ordenação manual (menor primeiro)'),
        ),
        migrations.AlterField(
            model_name='resultadoaluna',
            name='tecnica',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='servicoimagem',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.servico'),
        ),
    ]
